name: seqflow-merge

on:
  push:
    branches:
      - main

concurrency: seqflow-merge

permissions:
  contents: write
  packages: write

jobs:
  seqflow-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: greg-chuchro/seqflow-merge@v0.0
      with:
        callback: |
          PROJECT_FILE=$(find . -name *.*proj | grep --invert-match Test)
          NUPKG=$(dotnet pack "$PROJECT_FILE" --configuration Release -p:ContinuousIntegrationBuild=true -p:EmbedUntrackedSources=true -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:RepositoryUrl=${{github.repositoryUrl}} -p:RepositoryBranch=$BRANCH_NAME | sed -n "s/[^/]*\(\/.*\.nupkg\).*/\1/p")
          dotnet nuget push $NUPKG --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${{secrets.GITHUB_TOKEN}}
          git tag v$NEW_RELEASE_VERSION
          git push origin v$NEW_RELEASE_VERSION
