name: seqflow-merge

on:
  push:
    branches:
      - main

concurrency: seqflow-merge

permissions:
  contents: write
  packages: write

jobs:
  seqflow-merge:
    runs-on: ubuntu-latest
    steps:
    - name: setup nuget config
      run: dotnet nuget add source --username ${{github.triggering_actor}} --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: greg-chuchro/seqflow-merge@v0.0
      with:
        callback: |
          PROJECT_FILE=$(find . -name *.*proj | grep --invert-match Test)
          PROJECT_DIR=$(dirname $PROJECT_FILE)
          PROJECT_FILE_NAME=$(basename $PROJECT_FILE)
          PROJECT_NAME="${PROJECT_FILE_NAME%.*}"
          dotnet pack "$PROJECT_FILE" --configuration Release -p:ContinuousIntegrationBuild=true -p:EmbedUntrackedSources=true -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:RepositoryUrl=${{github.repositoryUrl}} -p:RepositoryBranch=$BRANCH_NAME
          WORKING_DIR=$PWD
          cd $PROJECT_DIR/bin/Release
          dotnet nuget push $PROJECT_NAME.$NEW_RELEASE_VERSION.nupkg --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${{secrets.GITHUB_TOKEN}}
          cd $WORKING_DIR
          git tag v$NEW_RELEASE_VERSION
          git push origin v$NEW_RELEASE_VERSION
